resources:
- ../../base/istory-app
- ../../base/istory-db

namespace: istory-dev

patches:
- path: patch-lb-annotations.yaml
  target:
    kind: Service
    name: istory-app-lb
- path: patch-deploy.yaml
  target:
    kind: Deployment
    name: istory-app-deploy

images:
- name: dangtong76/istory
  newName: dangtong76/istory
  newTag: "23"

generatorOptions:
  disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
